services:
  api:
    image: localhost/rss-api
    restart: always
    environment:
      - RSS_DB_HOSTNAME=db
      - RSS_DB_PORT=5432
      - RSS_DB_USER=rss_user
      - RSS_DB_PW_PATH=/run/secrets/db_user_pw
      - RSS_DB_NAME=rss_db
      - RSS_API_HOSTNAME=0.0.0.0
      - RSS_API_PORT=3001
      - RSS_API_AUTH_CONFIG=https://hostname/realms/my_realm/.well-known/openid-configuration
      - RSS_CORS_ORIGINS=http://localhost:3000
      - RSS_CORS_METHODS=GET
    ports:
      - 3001:3001
    secrets:
      - db_user_pw
  processor:
    image: localhost/rss-processor
    restart: always
    environment:
      - RSS_KAFKA_SERVER=broker:9092
      - RSS_KAFKA_TOPIC=rss-feed
      - RSS_KAFKA_GROUP_ID=rss-feed-group
      - RSS_DB_HOSTNAME=db
      - RSS_DB_PORT=5432
      - RSS_DB_USER=rss_user
      - RSS_DB_PW_PATH=/run/secrets/db_user_pw
      - RSS_DB_NAME=rss_db
      - RSS_DB_MIGRATE=true
    secrets:
      - db_user_pw
  collector:
    image: localhost/rss-collector
    restart: always
    environment:
      - RSS_YOUTUBE_NESSAJ_GAMING=UC1R3yteq3HoSUIHQ7hp65XQ
      - RSS_YOUTUBE_NESSAJ_REACTS=UCHnd8KvQyMGU0DAlJSuYwhw
      - RSS_YOUTUBE_NESSAJ=UCcSAt9uIqRHK8dEV2wVY1dQ
      - RSS_REDDIT_SELHOSTED=selfhosted/.rss
      - RSS_REDDIT_ANSIBLE=ansible/.rss
      - RSS_REDDIT_RUST=rust/.rss
      - RSS_REDDIT_GO=golang/.rss
      - RSS_STANDARD_1=https://www.gsplus.hu/site/rss/rss.xml
      - RSS_CRUNCHYROLL=true
      - RSS_KAFKA_SERVER=broker:9092
      - RSS_KAFKA_TOPIC=rss-feed
      - RSS_WAIT_SECONDS=60
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_user_pw
      POSTGRES_USER: rss_user
      POSTGRES_DB: rss_db
    secrets:
      - db_user_pw
  broker:
    image: apache/kafka
    hostname: broker
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://broker:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'

secrets:
  db_user_pw:
    file: .db.env