youtube:
- UC1R3yteq3HoSUIHQ7hp65XQ
- UCHnd8KvQyMGU0DAlJSuYwhw
- UCcSAt9uIqRHK8dEV2wVY1dQ
reddit:
- ansible/.rss
- selfhosted/.rss
- rust/.rss
standard:
- https://www.gsplus.hu/site/rss/rss.xml
crunchyroll: true
kafka:
  server: broker:9092
  topic: rss-feed
wait_seconds: 60
