db:
  hostname: db
  port: 5432
  user: rss_user
  password_path: ./.db.env
  db_name: rss_db
api:
  hostname: localhost
  port: 3000
  auth_config: https://auth.thinkaboutit.tech/realms/dev/.well-known/openid-configuration
cors:
  origins: http://localhost:5500
  methods: GET
