name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: allow write access to checks to allow the action to annotate code in the PR.
  checks: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run Go Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - name: Go code formatting
        run: |
          gofmt -l -s -d .

      - name: Verify Go Dependencies
        run: |
          go mod tidy
          go mod verify

      - name: Run Tests
        run: go test ./... -v

      - name: Build Binary
        run: |
          go build -o rss-api ./cmd/rss-api
          go build -o rss-collector ./cmd/rss-collector
          go build -o rss-processor ./cmd/rss-processor
        