name: Release the version of software

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to rebuild and push"
        required: true
        default: "v1.0.0"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: collector
            image: onlyati/rss-collector
            dockerfile: ./cmd/rss-collector/Dockerfile
          - service: processor
            image: onlyati/rss-processor
            dockerfile: ./cmd/rss-processor/Dockerfile
          - service: api
            image: onlyati/rss-api
            dockerfile: ./cmd/rss-api/Dockerfile
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{ inputs.version }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
      - name: Build container
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{ matrix.dockerfile }}
