name: Release the version of software

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:

jobs:
  test_meta:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: collector
            image: onlyati/rss-collector
            dockerfile: ./cmd/rss-collector/Dockerfile
          - service: processor
            image: onlyati/rss-processor
            dockerfile: ./cmd/rss-processor/Dockerfile
          - service: api
            image: onlyati/rss-api
            dockerfile: ./cmd/rss-api/Dockerfile
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=semver,pattern={{inputs.version}}
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}